name: WalletIOS-SDK-Tests

on:
  pull_request:
    branches:
      - main
      - release/**
jobs:
  tests-ios-sdk:
    runs-on: macos-15
    env:
      XC_VERSION: "16.4"
    steps:
      # Git clone repository
      - name: Git clone repository
        uses: actions/checkout@v4
      # Select latest Xcode
      - name: Select latest Xcode
        run: "sudo xcode-select -s /Applications/Xcode_${{ env.XC_VERSION }}.app"
      - name: Run tests
        run: xcodebuild test -project VCLAuth.xcodeproj -scheme VCLAuth -destination 'platform=iOS Simulator,name=iPhone 17,OS=18.6'
        working-directory: VCLAuth
